url: http://chennaimakerspace.com

# Site settings
title: Chennai Makerspace 
email: makeinchennai@gmail.com
description: "Bringing the Maker Community to Namma Chennai one bot at a time."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Tamil Kadir Rajavel
  pic: tk
  position: Embeddded Software Engineer, Rockwell Automation
  social:
    - title: facebook
      url:  https://www.facebook.com/ignitedindian
    - title: linkedin
      url: https://www.linkedin.com/in/tamilkadir
- name: Ramesh Ramamoorthy 
  pic: ramesh
  position: Deputy Manager, BGR Energy Systems Ltd.
  social:
    - title: facebook
      url:  https://www.facebook.com/ramesh.ramamoorthy
- name: Dr.Senthilkumaran Mahadevan
  pic: senthil
  position: Associate Professor, SSNCE
  social:
    - title: facebook
      url:  https://www.facebook.com/profile.php?id=100004215948948
    - title: university 
      url: http://www.ssn.edu.in/?page_id=2138

makers:
- name: Saipraveen Durairaman
  pic: sai
  social:
    - title: github
      url: https://www.github.com/saipraveend
    - title: facebook
      url:  https://www.facebook.com/saipraveen.durairaman/
    - title: linkedin
      url: https://linkedin.com/in/saipraveend
- name: Karthik Singaram
  pic: karthik
  social:
    - title: facebook
      url:  https://www.facebook.com/karthik.singaram.5/
    - title: linkedin
      url: https://in.linkedin.com/pub/karthik-singaram-rathinam/102/582/19
- name: Sibi Sankar
  pic: sibi
  social:
    - title: github
      url:  https://www.github.com/quinasura
    - title: facebook
      url:  https://www.facebook.com/sibisank/
    - title: linkedin
      url: https://linkedin.com/in/sibisankar
- name: Vijayenthiran Subramaniam
  pic: vijay
  social:
    - title: github
      url:  https://github.com/Vijayenthiran
    - title: facebook
      url:  https://www.facebook.com/Vijayenthiran/
    - title: linkedin
      url:  https://in.linkedin.com/in/vijayenthiran
- name: Adithya Selvaprithiviraj
  pic: adithya
  social:
    - title: github
      url:  https://www.github.com/adithyaselv
    - title: facebook
      url: https://www.facebook.com/adithya.selv/
    - title: linkedin
      url:  https://linkedin.com/in/adithyaselv
- name: Mervin J.B
  pic: mervin
  social:
    - title: facebook
      url:  https://www.facebook.com/mervin.rodrigo.5
    - title: linkedin
      url: https://in.linkedin.com/pub/mervin-j-b/19/b39/b0a
- name: Imthiaz Ahmed
  pic: imthi
  social:
    - title: facebook
      url:  https://www.facebook.com/aimthiazz
    - title: linkedin
      url:  https://in.linkedin.com/in/aimthiazz
- name: Sudhir Matta
  pic: sudir
  social:
    - title: facebook
      url: https://www.facebook.com/5udhiR
- name: Sanjay Shreedharan
  pic: sanjay
  social:
    - title: facebook
      url:  https://www.facebook.com/shridharsanjay1994
    - title: linkedin
      url: https://in.linkedin.com/pub/sanjay-shreedharan/85/4b0/178


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Chennaimakers
  - title: github
    url: http://github.com/chennaimakerspace

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
