url: http://www.chennaimakerspace.com 

# Site settings
title: Chennai Maker Space 
email: makeinchennai@gmail.com
description: "Bringing the Maker Community to Namma Chennai one bot at a time."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Tamil Kadir Rajavel
  pic: tk
  social:
    - title: facebook
      url:  https://www.facebook.com/ignitedindian
    - title: linkedin
      url: https://www.linkedin.com/in/tamilkadir
- name: Ramesh Ramamoorthy 
  pic: ramesh
  social:
    - title: facebook
      url:  https://www.facebook.com/ramesh.ramamoorthy
- name: Senthilkumaran Mahadevan
  pic: senthil
  social:
    - title: facebook
      url:  https://www.facebook.com/profile.php?id=100004215948948


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Chennaimakers
  - title: github
    url: http://github.com/chennaimakerspace

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
